version: "3.8"

services:
  pub-sub:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "src"
        target: "/go/app/src"
    depends_on:
      - queue

  queue:
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - type: bind
        source: "elasticmq.conf"
        target: "/opt/elasticmq.conf"
